// AUTH
export const REGISTER = 'REGISTER';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const CLEARERROR = 'CLEARERROR';

// USER
export const USERLOADED = 'USERLOADED';

// MUSIC
export const GET_MUSIC_ALL = 'GET_MUSIC_ALL';
export const ADD_MUSIC = 'ADD_MUSIC';
export const ADD_ARTIST = 'ADD_ARTIST';
export const GET_ARTIST = 'GET_ARTIST';
export const GET_CATEGORY = 'GET_CATEGORY';

// TRANSAKSI
export const GET_TRANSACTION = 'GET_TRANSACTION';
export const CREATE_TRANSACTION = 'CREATE_TRANSACTION';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const ONE_TRANSACTION = 'ONE_TRANSACTION';
